Add playwright install as postinstall script
Unlike Cypress which expects you to install the browsers you intend to test with, Playwright installs its own.

If you don't run `playwright install`, none of the Playwright tests will run, and you'll get an error like this:

```text
Error: Failed to launch the browser. Please run "npx playwright install" to install the browsers.
```

But this project is predominantly for our QA team, so we need to make the process as slick as possible. By adding `playwright install` as a postinstall script, we ensure that the browsers are installed automatically when the project is set up.

To do this though, we have also had to approve a new package in the `allowScripts` section of `package.json`, which is `unrs-resolver@1.12.2`. This is because Playwright uses this package to resolve the browsers it needs to install.